// frontend2/src/lib/components/news.svelte
<script lang="ts">
	import { getContextClient, queryStore } from '@urql/svelte';

	import { getIndexStore } from '$lib/stores/news';
	import { screen } from '$lib/stores/screen';

	import { BASE_URL } from '$lib/client';
	import { GET_NEWS, type GetNewsData, type NewsItem } from '$lib/models/news';

	export let params: string = '';

	const MAX_ITEMS = 3;

	$: store = queryStore<GetNewsData>({
		query: GET_NEWS,
		variables: { feed: params },
		context: { additionalTypenames: ['NewsItem'] },
		client: getContextClient()
	});

	let selectedItem: NewsItem | null = null;

	$: rawNews = $store.data?.news || [];
	$: index = getIndexStore(params);
	$: newsIdx = ($index < 0 ? rawNews.length : 0) + ($index % rawNews.length);
	$: news = [
		...rawNews.slice(newsIdx, newsIdx + MAX_ITEMS),
		...rawNews.slice(0, Math.max(MAX_ITEMS - (rawNews.length - newsIdx), 0))
	];

	let startY = 0;
	const touchStart = (e: TouchEvent) => {
		startY = e.changedTouches[0].clientY;
	};
	const touchEnd = (e: TouchEvent) => {
		const diff = e.changedTouches[0].clientY - startY;
		if (diff < -100) {
			index.increment();
			screen.reset();
		} else if (diff > 100) {
			index.decrement();
			screen.reset();
		}
	};

	const select = (item: NewsItem | null) => {
		selectedItem = item;
		if (item) {
			screen.stop();
		} else {
			screen.start();
		}
	};
</script>

<div class="container" on:touchstart={touchStart} on:touchend={touchEnd}>
	{#if selectedItem}
		<div class="details">
			<iframe title="Story" src={BASE_URL + selectedItem.link} />
			<button class="close" on:click={() => select(null)}>❌</button>
		</div>
	{:else}
		{#each news as item}
			<div class="item" on:click={() => select(item)} on:keypress={() => select(item)}>
				<img class="image" alt="Thumbnail" src={item.img} />
				<div class="abstract">{item.title}</div>
			</div>
		{/each}
	{/if}
</div>

<style>
	.container {
		flex: 1;
		display: flex;
		flex-direction: column;
		justify-content: space-between;
		overflow: hidden;
	}

	.item {
		flex: 1;
		display: flex;
		flex-direction: row;
		align-items: center;
		overflow: hidden;
		margin-top: 0.5rem;
	}

	img.image {
		height: 100%;
		margin-right: 0.5rem;
	}

	.abstract {
		flex: 4;
		font-size: 1.2rem;
		line-height: 1.2rem;
	}

	iframe {
		width: 100%;
		height: 100%;
		border: 1px solid gray;
	}

	.details {
		position: absolute;
		top: 8px;
		left: 8px;
		right: 8px;
		bottom: 8px;
	}

	button.close {
		position: absolute;
		top: 8px;
		left: 8px;
		font-size: 1rem;
	}
</style>

// frontend/src/app/news.tsx
import { styled } from '@stitches/react';
import React, { FC, TouchEvent, useCallback, useEffect, useState } from 'react';

import { BASE_URL, NewsItem, useNews } from './api';

const Container = styled('div', {
	flex: 1,
	display: 'flex',
	flexDirection: 'column',
	justifyContent: 'space-between',
	overflow: 'hidden'
});

const Item = styled('div', {
	flex: 1,
	display: 'flex',
	flexDirection: 'row',
	alignItems: 'center',
	overflow: 'hidden',
	marginTop: 10
});

const Image = styled('img', {
	height: '100%',
	marginRight: 10
});

const Abstract = styled('div', {
	flex: 4,
	fontSize: 38,
	lineHeight: '1.1em'
});

const IFrame = styled('iframe', {
	width: '100%',
	height: '100%',
	borderWidth: 1,
	borderStyle: 'solid',
	borderColor: 'gray'
});

const DetailContainer = styled('div', {
	position: 'absolute',
	top: 10,
	left: 10,
	right: 10,
	bottom: 10
});

const CloseButton = styled('button', {
	position: 'absolute',
	top: 10,
	left: 10,
	fontSize: 40
});

interface Props {
	id: string;
	onRequestPause: (pause: boolean) => void;
}

const ITEMS = 2;
const idxMap: Map<string, number> = new Map();

export const News: FC<Props> = ({ id, onRequestPause }) => {
	const news = useNews(id);
	const [item, setItem] = useState<NewsItem | null>(null);
	const [startY, setStartY] = useState(0);

	const inc = useCallback(
		(num: number) => {
			const currIdx = idxMap.get(id);
			const newIdx = typeof currIdx == 'number' ? currIdx + num * ITEMS : ITEMS;
			idxMap.set(id, newIdx);
		},
		[id]
	);

	useEffect(() => inc(1), [id]);

	const touchStart = useCallback(
		(e: TouchEvent<HTMLDivElement>) => {
			setStartY(e.changedTouches[0].clientY);
		},
		[setStartY]
	);
	const touchEnd = useCallback(
		(e: TouchEvent<HTMLDivElement>) => {
			const diff = e.changedTouches[0].clientY - startY;
			if (diff < -100) {
				inc(1);
			} else if (diff > 100) {
				inc(-1);
			}
		},
		[inc, startY]
	);

	useEffect(() => {
		onRequestPause(!!item);
	}, [item]);

	const idx = (idxMap.get(id) || 0) % (news.length - ITEMS + 1 || 1);

	return (
		<Container onTouchStart={touchStart} onTouchEnd={touchEnd}>
			{item ? (
				<DetailContainer>
					<IFrame src={BASE_URL + item.link} />
					<CloseButton onClick={() => setItem(null)}>❌</CloseButton>
				</DetailContainer>
			) : (
				news.slice(idx, idx + ITEMS).map((item) => (
					<Item key={item.title} onClick={() => setItem(item)}>
						<Image src={item.img} />
						<Abstract>{item.title}</Abstract>
					</Item>
				))
			)}
		</Container>
	);
};
