// frontend/src/weather.tsx
import { styled } from '@stitches/react';
import axios from 'axios';
import { add, format, isAfter, parseISO, startOfDay } from 'date-fns';
import { de } from 'date-fns/locale';
import React, { FC, useEffect, useState } from 'react';

import { BASE_URL } from './const';

interface WeatherEntry {
	time: Date;
	img: string;
	feelsLike: number;
}

const useWeather = (): WeatherEntry[] => {
	const [items, setItems] = useState<WeatherEntry[]>([]);

	useEffect(() => {
		const main = async () => {
			const { data } = await axios(`${BASE_URL}/weather`);
			setItems(
				data.forecasts.map((f: { time: string; img: string; feelsLike: number }) => ({ ...f, time: parseISO(f.time) }))
			);
		};

		main().catch((err) => console.error(err));
	}, []);

	return items;
};

type DateCompare = (now: Date, date: Date) => boolean;
const WEATHER_FORECASTS: DateCompare[] = [
	(now, date) => isAfter(date, startOfDay(now)),
	(now, date) => isAfter(date, startOfDay(add(now, { days: 1 }))),
	(now, date) => isAfter(date, startOfDay(add(now, { days: 2 }))),
	(now, date) => isAfter(date, startOfDay(add(now, { days: 3 }))),
	(now, date) => isAfter(date, startOfDay(add(now, { days: 4 })))
];

const Container = styled('div', {
	flex: 1,
	display: 'flex',
	flexDirection: 'row',
	justifyContent: 'space-between',
	alignItems: 'stretch'
});
const Forecast = styled('div', {
	flex: 1,
	display: 'flex',
	flexDirection: 'column'
});
const ForecastImg = styled('i', {
	fontSize: '10em !important',
	textAlign: 'center'
});
const ForecastText = styled('div', {
	fontSize: 60,
	textAlign: 'center',
	marginTop: 40
});

export const Weather: FC = () => {
	const forecasts = useWeather();

	const now = new Date();
	const shownForecasts = WEATHER_FORECASTS.map((dateCompare) =>
		forecasts.find((forecast) => dateCompare(now, forecast.time))
	).filter((forecast) => !!forecast) as WeatherEntry[];

	return (
		<Container>
			{shownForecasts.map((forecast) => (
				<Forecast key={forecast.time.toISOString()}>
					<ForecastText style={{ flex: 1 }}>{format(forecast.time, 'iiiiii', { locale: de })}</ForecastText>
					<ForecastImg className={`owf owf-${forecast.img}`} />
					<ForecastText style={{ flex: 0.8, color: '#23ad00' }}>{forecast.feelsLike.toFixed(0)}°</ForecastText>
				</Forecast>
			))}
		</Container>
	);
};

// frontend2/src/routes/weather/+page.svelte
<script lang="ts">
	import { format, parseISO } from 'date-fns';
	import { de } from 'date-fns/locale';

	import type { PageData } from './$types';

	export let data: PageData;

	const NUM_FORECASTS = 5;

	$: weather = data.weather;
	$: temp = weather?.temp;
	$: rh = weather?.rh;

	$: numForecasts = NUM_FORECASTS - (temp || rh ? 2 : 0);
	$: forecasts = weather?.forecasts.slice(0, numForecasts) || [];
</script>

<div class="container">
	<div class="sensors">
		<div class="text" style="color: #23ad00">{temp?.toFixed(0)}°</div>
		<div class="text" style="color: #0052d6">{rh?.toFixed(0)}%</div>
	</div>

	<div class="forecasts">
		{#each forecasts as forecast}
			<div class="forecast">
				<div class="text">{format(parseISO(forecast.ts), 'iiiiii', { locale: de })}</div>
				<img src={forecast.img} alt="Weather icon" />
				<div class="text" style="color: #23ad00">{forecast.feelsLike.toFixed(0)}°</div>
			</div>
		{/each}
	</div>
</div>

<style>
	.container {
		flex: 1;
		display: flex;
		flex-direction: row;
	}

	.sensors {
		flex: 1;
		display: flex;
		flex-direction: column;
		justify-content: space-evenly;
		align-items: center;
	}

	.sensors > .text {
		font-size: 100px;
		text-align: center;
	}

	.forecasts {
		flex: 3;
		display: flex;
		flex-direction: row;
		justify-content: space-evenly;
		align-items: stretch;
	}

	.forecast {
		flex: 1;
		display: flex;
		flex-direction: column;
		justify-content: space-evenly;
		align-items: center;
	}

	.forecast > img {
		width: 80%;
	}

	.forecast > .text {
		font-size: 80px;
		text-align: center;
	}
</style>
